- name: Deploy Hostel Outpass App (Model A)
  hosts: app
  become: yes

  vars:
    app_dir: /home/ubuntu/hostel-app
    repo_url: https://github.com/Mithunit18/hostel-management.git
    live_color: "blue"   # change to green to switch

  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone project repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Pull latest Docker images
      command: docker compose pull
      args:
        chdir: "{{ app_dir }}"

    - name: Render nginx config (blue-green)
      template:
        src: hostel.conf.j2
        dest: "{{ app_dir }}/nginx/hostel.conf"


    - name: Start or update containers (no downtime)
      command: docker compose up -d
      args:
        chdir: "{{ app_dir }}"

    - name: Reload nginx container only
      command: docker compose up -d nginx
      args:
        chdir: "{{ app_dir }}"
